name: Fetch Facebook API Data

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  run-fetch-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      run: python fetch_data.py
      env:
        FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }} 

    - name: Upload JSON file
      uses: actions/upload-artifact@v3
      with:
        name: output_data
        path: output_data.json  # 指定生成的 JSON 文件路径

    - name: Commit and push changes
      run: |
        git config --global glossimute 'github-actions[bot]'
        git config --global lifepattern_@outlook.com 'github-actions[bot]@users.noreply.github.com'
        git add output_data.json
        git commit -m "Update output data (JSON)"
        git push
