name: Fetch Facebook API Data

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed
  workflow_dispatch:

permissions:
  issues: write
  
jobs:
  run-fetch-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install pytz

    - name: Run script
      run: python fetch_data.py
      env:
        FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }} 
        URL: ${{ secrets.URL }} 



    
    - name: Add comment to Issue in private repo
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.PERSONAL_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/robot4black/insfollowerscount/issues/1/comments \
        -d '{"body":"This is a comment from the public repo workflow!"}'
